field: 7db71904-a388-4646-9119-eeea53f9a860 # Page Blocks
fieldLayouts:
  dffe69d1-017d-46fb-a563-31fadda0b393:
    tabs:
      -
        elements:
          -
            fieldUid: 7d50668e-f1a7-41f2-ac7a-02e7ffe1ad46 # Unit ID
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  7d50668e-f1a7-41f2-ac7a-02e7ffe1ad46: # Unit ID
    columnSuffix: wtauqnkj
    contentColumnType: text
    fieldGroup: null
    handle: unitId
    instructions: ''
    name: 'Unit ID'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: faq
name: FAQ
sortOrder: 5
