field: 7db71904-a388-4646-9119-eeea53f9a860 # Page Blocks
fieldLayouts:
  5feb8fcf-b9ff-48d4-bb18-8ce4f65399c2:
    tabs:
      -
        elements:
          -
            fieldUid: 33947576-62eb-4845-88b2-687797d6c246 # Unit ID
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: c8def145-282f-4686-bde6-1a1d18c37efb # Headline
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  33947576-62eb-4845-88b2-687797d6c246: # Unit ID
    columnSuffix: omyxbkvf
    contentColumnType: text
    fieldGroup: null
    handle: unitId
    instructions: ''
    name: 'Unit ID'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  c8def145-282f-4686-bde6-1a1d18c37efb: # Headline
    columnSuffix: dgbfefwx
    contentColumnType: text
    fieldGroup: null
    handle: headline
    instructions: ''
    name: Headline
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: header
name: Header
sortOrder: 2
