field: 78888197-26c5-4cfa-bc9e-acb8a24d0bc3 # Blocks
fieldLayouts:
  09930dcd-a410-4e5b-94e3-bf06f47b4ede:
    tabs:
      -
        elements:
          -
            fieldUid: 2064df9b-8d43-46b0-8ebf-77d94a8b5479 # Slider Title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: d8908cbd-ae7e-4778-b10d-2451f45de857 # Slider Matrix
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  2064df9b-8d43-46b0-8ebf-77d94a8b5479: # Slider Title
    columnSuffix: ucjyoske
    contentColumnType: text
    fieldGroup: null
    handle: sliderTitle
    instructions: ''
    name: 'Slider Title'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  d8908cbd-ae7e-4778-b10d-2451f45de857: # Slider Matrix
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: sliderMatrix
    instructions: ''
    name: 'Slider Matrix'
    searchable: false
    settings:
      columns:
        __assoc__:
          -
            - af833e7a-e9a4-4544-9622-9ae220acdc95 # Text Sub
            -
              __assoc__:
                -
                  - width
                  - ''
          -
            - 4ef6bb87-f4cd-4616-9bda-46bd523e9962 # Text Heading
            -
              __assoc__:
                -
                  - width
                  - ''
          -
            - b2fc737a-5c4d-43c3-9f2a-a83984420667 # Text Background
            -
              __assoc__:
                -
                  - width
                  - ''
          -
            - d8d9f665-6ed7-4a01-8f68-5295fe71b7e0 # Slide Image
            -
              __assoc__:
                -
                  - width
                  - ''
      contentTable: '{{%stc_3_slidermatrix}}'
      fieldLayout: matrix
      maxRows: ''
      minRows: ''
      placeholderKey: null
      propagationKeyFormat: null
      propagationMethod: all
      selectionLabel: ''
      staticField: ''
    translationKeyFormat: null
    translationMethod: site
    type: verbb\supertable\fields\SuperTableField
handle: imageSlider
name: 'Image Slider'
sortOrder: 3
