field: 78888197-26c5-4cfa-bc9e-acb8a24d0bc3 # Blocks
fieldLayouts:
  e5bac886-150b-454e-a078-c206ba00958f:
    tabs:
      -
        elements:
          -
            fieldUid: 9c402a93-b3e7-4113-a514-de877143610d # Heading
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 7ac46c41-4c27-4c1b-84df-e54dba8bacfd # Speakers Intro
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 84343fee-3a4a-4617-97af-d90bc4108bcf # Speakers
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  7ac46c41-4c27-4c1b-84df-e54dba8bacfd: # Speakers Intro
    columnSuffix: jmsxubrc
    contentColumnType: text
    fieldGroup: null
    handle: speakersIntro
    instructions: 'Intro text for the speaker component. Optional. '
    name: 'Speakers Intro'
    searchable: false
    settings:
      availableTransforms: '*'
      availableVolumes: '*'
      columnType: text
      configSelectionMode: choose
      defaultTransform: ''
      manualConfig: ''
      purifierConfig: ''
      purifyHtml: '1'
      redactorConfig: ''
      removeEmptyTags: '1'
      removeInlineStyles: '1'
      removeNbsp: '1'
      showHtmlButtonForNonAdmins: ''
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      uiMode: enlarged
    translationKeyFormat: null
    translationMethod: none
    type: craft\redactor\Field
  9c402a93-b3e7-4113-a514-de877143610d: # Heading
    columnSuffix: kengwaoa
    contentColumnType: text
    fieldGroup: null
    handle: heading
    instructions: ''
    name: Heading
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  84343fee-3a4a-4617-97af-d90bc4108bcf: # Speakers
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: speakers
    instructions: ''
    name: Speakers
    searchable: false
    settings:
      allowSelfRelations: false
      limit: ''
      localizeRelations: false
      selectionLabel: ''
      showSiteMenu: true
      source: null
      sources:
        - 'section:cc1499b1-8d66-4731-b6e6-9df288ebf714' # Speakers
      targetSiteId: null
      validateRelatedElements: false
      viewMode: null
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Entries
handle: speakers
name: Speakers
sortOrder: 5
