field: 78888197-26c5-4cfa-bc9e-acb8a24d0bc3 # Blocks
fieldLayouts:
  46a8a98b-fd94-4ef1-b73c-42d43e5d2bd1:
    tabs:
      -
        elements:
          -
            fieldUid: 4f3df36c-28b5-4f40-9dec-24f89271a732 # Headline
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: ddaf97aa-ecdf-4dc4-b907-37241a3b6343 # ArticleBody
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  4f3df36c-28b5-4f40-9dec-24f89271a732: # Headline
    columnSuffix: pqybyjzi
    contentColumnType: text
    fieldGroup: null
    handle: headline
    instructions: ''
    name: Headline
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  ddaf97aa-ecdf-4dc4-b907-37241a3b6343: # ArticleBody
    columnSuffix: cptqwoxr
    contentColumnType: text
    fieldGroup: null
    handle: articleBody
    instructions: ''
    name: ArticleBody
    searchable: false
    settings:
      availableTransforms: '*'
      availableVolumes: '*'
      columnType: text
      configSelectionMode: choose
      defaultTransform: ''
      manualConfig: ''
      purifierConfig: ''
      purifyHtml: '1'
      redactorConfig: ''
      removeEmptyTags: '1'
      removeInlineStyles: '1'
      removeNbsp: '1'
      showHtmlButtonForNonAdmins: ''
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      uiMode: enlarged
    translationKeyFormat: null
    translationMethod: none
    type: craft\redactor\Field
handle: text
name: Text
sortOrder: 6
