field: 78888197-26c5-4cfa-bc9e-acb8a24d0bc3 # Blocks
fieldLayouts:
  5bbb9716-4a6a-4256-af4d-1bbc67cd69a2:
    tabs:
      -
        elements:
          -
            fieldUid: 9f4ae9fd-9ec5-4570-b0ac-d857dfd0b6aa # Unit Id
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: e79c85f5-481c-48b5-81b6-967064995904 # Text Visual Title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 48f64521-1a89-4e88-8570-b84fb02fb07d # Text Visual Content
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 8e796a89-b670-45ce-b932-334adc605154 # Text Visual Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: e9bc3994-4748-47b3-a2dc-58d2e60bbc7a # Text Visual Buttons
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  8e796a89-b670-45ce-b932-334adc605154: # Text Visual Image
    columnSuffix: hxecwwau
    contentColumnType: text
    fieldGroup: null
    handle: textVisualImage
    instructions: ''
    name: 'Text Visual Image'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  9f4ae9fd-9ec5-4570-b0ac-d857dfd0b6aa: # Unit Id
    columnSuffix: lhnepvmj
    contentColumnType: text
    fieldGroup: null
    handle: unitId
    instructions: ''
    name: 'Unit Id'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  48f64521-1a89-4e88-8570-b84fb02fb07d: # Text Visual Content
    columnSuffix: elumpqdb
    contentColumnType: text
    fieldGroup: null
    handle: textVisualContent
    instructions: ''
    name: 'Text Visual Content'
    searchable: false
    settings:
      availableTransforms: '*'
      availableVolumes: '*'
      columnType: text
      configSelectionMode: choose
      defaultTransform: ''
      manualConfig: ''
      purifierConfig: ''
      purifyHtml: '1'
      redactorConfig: ''
      removeEmptyTags: '1'
      removeInlineStyles: '1'
      removeNbsp: '1'
      showHtmlButtonForNonAdmins: ''
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      uiMode: enlarged
    translationKeyFormat: null
    translationMethod: none
    type: craft\redactor\Field
  e9bc3994-4748-47b3-a2dc-58d2e60bbc7a: # Text Visual Buttons
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: textVisualButtons
    instructions: ''
    name: 'Text Visual Buttons'
    searchable: false
    settings:
      contentTable: '{{%stc_textvisualbuttons}}'
      fieldLayout: matrix
      maxRows: ''
      minRows: ''
      placeholderKey: null
      propagationKeyFormat: null
      propagationMethod: all
      selectionLabel: ''
      staticField: ''
    translationKeyFormat: null
    translationMethod: site
    type: verbb\supertable\fields\SuperTableField
  e79c85f5-481c-48b5-81b6-967064995904: # Text Visual Title
    columnSuffix: etccqqvk
    contentColumnType: text
    fieldGroup: null
    handle: textVisualTitle
    instructions: ''
    name: 'Text Visual Title'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: textVisual
name: 'Text Visual'
sortOrder: 6
