fieldLayouts:
  c713f869-b6c0-4cfb-bd54-8066942c975a:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\EntryTitleField
            warning: null
            width: 100
          -
            fieldUid: 8a00143c-d0ca-420f-bd33-8bed0b046e07 # Author Name
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: b92f2c70-6612-4494-b3f5-7fccfd6d38c6 # Author First Name
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 6e5121f2-2ee7-4371-8f40-34c1b4b3705c # Author Last Name
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 7641ba6c-da21-49bc-b8d2-a8d4eeebdecd # Author Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 50
          -
            fieldUid: fca96965-882f-4612-8517-144a5bf4356f # Author Type
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 50
          -
            fieldUid: 3c64ffa3-ee5d-482e-a0ea-6dc7b2cef996 # Author Bio
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 7e672484-864b-498b-89ef-5a30f54143cd # Author Socials
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
handle: authors
hasTitleField: false
name: Authors
section: 3006cf88-6778-48e6-972a-19e9b65c2838 # Authors
sortOrder: 1
titleFormat: '{authorName}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
