fieldLayouts:
  b3791b56-baf8-4175-b771-380906123a24:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\EntryTitleField
            warning: null
            width: 100
          -
            heading: 'Speaker Details'
            type: craft\fieldlayoutelements\Heading
          -
            fieldUid: ac4cdd5d-e959-4928-a8c0-f856638f112a # Speaker Name
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 3063ba7e-ab58-42a0-b6fd-98d35de5bc3d # Speaker Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 2de52828-7907-4fe9-b689-e29d44f2662c # Speaker Bio
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: d75eadc7-ac0d-4a98-b2ca-611b839e3bd6 # Speaker Company
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: a9ea1239-f6bf-48e5-9a34-924440bc8cf5 # Company Url
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 809e8d90-be53-4bfc-8e85-2ac295f87b92 # Speaker Category
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
handle: speakers
hasTitleField: false
name: Speakers
section: cc1499b1-8d66-4731-b6e6-9df288ebf714 # Speakers
sortOrder: 1
titleFormat: '{speakerName}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
