defaultPlacement: end
fieldLayouts:
  84be37c8-9dc7-4138-b47d-ac28c2c030d1:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\TitleField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
handle: editorial
name: Editorial
siteSettings:
  d7c059b5-7d24-48d7-97bf-9dfca0e647ca: # nitroblog
    hasUrls: true
    template: null
    uriFormat: 'editorial/{slug}'
structure:
  maxLevels: null
  uid: edf1735d-fb23-41f0-9c96-49368a21427a
