columnSuffix: hterzlom
contentColumnType: string
fieldGroup: c4827951-7c23-426e-9af7-a47f10a48ed3 # Articles
handle: articleFormat
instructions: 'Selected the article format to output. Ex: text, video, audio'
name: 'Article Format'
searchable: false
settings:
  optgroups: true
  options:
    -
      __assoc__:
        -
          - label
          - Text
        -
          - value
          - text
        -
          - default
          - '1'
    -
      __assoc__:
        -
          - label
          - Video
        -
          - value
          - video
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - Audio
        -
          - value
          - audio
        -
          - default
          - ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\Dropdown
