columnSuffix: tfrwhomv
contentColumnType: text
fieldGroup: d446bb31-38e3-4f89-9ec4-17680bee8da4 # Authors
handle: authorFirstName
instructions: ''
name: 'Author First Name'
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: null
  initialRows: '4'
  multiline: ''
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
