columnSuffix: gljvgoqi
contentColumnType: boolean
fieldGroup: c4827951-7c23-426e-9af7-a47f10a48ed3 # Articles
handle: enabledRelated
instructions: ''
name: 'Enable Manual Related Articles'
searchable: false
settings:
  default: false
  offLabel: null
  onLabel: null
translationKeyFormat: null
translationMethod: none
type: craft\fields\Lightswitch
