columnSuffix: xsmbebsi
contentColumnType: text
fieldGroup: c4827951-7c23-426e-9af7-a47f10a48ed3 # Articles
handle: excerpt
instructions: ''
name: Excerpt
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: null
  initialRows: '4'
  multiline: ''
  placeholder: null
  uiMode: enlarged
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
