columnSuffix: null
contentColumnType: string
fieldGroup: b31ad286-c191-45ad-9f54-eeb20ae52ed5 # Blocks
handle: pageBlocks
instructions: ''
name: 'Page Blocks'
searchable: false
settings:
  contentTable: '{{%matrixcontent_pageblocks}}'
  maxBlocks: ''
  minBlocks: ''
  propagationKeyFormat: null
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
