columnSuffix: null
contentColumnType: string
fieldGroup: c1bb4e2d-2c53-48de-8a84-a21a5ec47734 # Blocks
handle: pageBlocks
instructions: ''
name: Blocks
searchable: false
settings:
  contentTable: '{{%matrixcontent_pageblocks}}'
  maxBlocks: ''
  minBlocks: ''
  propagationKeyFormat: null
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
