columnSuffix: null
contentColumnType: string
fieldGroup: c4827951-7c23-426e-9af7-a47f10a48ed3 # Articles
handle: tags
instructions: ''
name: Tags
searchable: false
settings:
  allowLimit: false
  allowMultipleSources: false
  allowSelfRelations: false
  limit: null
  localizeRelations: false
  selectionLabel: ''
  showSiteMenu: true
  source: 'taggroup:4e501aba-6e6b-42e4-8047-304e0b576a79' # Latest
  sources: '*'
  targetSiteId: null
  validateRelatedElements: false
  viewMode: null
translationKeyFormat: null
translationMethod: site
type: craft\fields\Tags
