field: e9bc3994-4748-47b3-a2dc-58d2e60bbc7a # Text Visual Buttons
fieldLayouts:
  7f8146eb-c2c4-4fdc-9790-ec8ee11f740c:
    tabs:
      -
        elements:
          -
            fieldUid: 45376496-3fb2-4d0c-b143-dff5f5cd2326 # Link Id
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: aa6ce88c-2bcc-4afd-a0aa-2573e87b6e1e # Link Text
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 8b590b8e-114a-4fc1-8f65-e4cb7d55a31a # Link Url
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 7f04efa5-3c71-4d26-b19c-2ea158ff475d # Target
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  7f04efa5-3c71-4d26-b19c-2ea158ff475d: # Target
    columnSuffix: wrfstnww
    contentColumnType: text
    fieldGroup: null
    handle: target
    instructions: ''
    name: Target
    searchable: false
    settings:
      multi: true
      options:
        -
          __assoc__:
            -
              - label
              - 'Is External'
            -
              - value
              - isExternal
            -
              - default
              - ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Checkboxes
  8b590b8e-114a-4fc1-8f65-e4cb7d55a31a: # Link Url
    columnSuffix: ubsejifk
    contentColumnType: text
    fieldGroup: null
    handle: linkUrl
    instructions: ''
    name: 'Link Url'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  45376496-3fb2-4d0c-b143-dff5f5cd2326: # Link Id
    columnSuffix: apgosbao
    contentColumnType: text
    fieldGroup: null
    handle: linkId
    instructions: ''
    name: 'Link Id'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  aa6ce88c-2bcc-4afd-a0aa-2573e87b6e1e: # Link Text
    columnSuffix: kkmhhmdk
    contentColumnType: text
    fieldGroup: null
    handle: linkText
    instructions: ''
    name: 'Link Text'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
