field: 7e672484-864b-498b-89ef-5a30f54143cd # Author Socials
fieldLayouts:
  d6656ccc-e4e5-4f6c-bef8-21397f62f91d:
    tabs:
      -
        elements:
          -
            fieldUid: 124b328d-357a-4716-b617-457f589e5fad # Platform Name
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 3fcb9ba5-732f-4d73-b23d-475425665566 # Platform Logo
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 8066ba82-b555-4b6d-a80e-d626af0a5636 # Author Link
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  3fcb9ba5-732f-4d73-b23d-475425665566: # Platform Logo
    columnSuffix: fnnpxzge
    contentColumnType: text
    fieldGroup: null
    handle: platformLogo
    instructions: ''
    name: 'Platform Logo'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  124b328d-357a-4716-b617-457f589e5fad: # Platform Name
    columnSuffix: zjqkfpnd
    contentColumnType: text
    fieldGroup: null
    handle: platformName
    instructions: ''
    name: 'Platform Name'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  8066ba82-b555-4b6d-a80e-d626af0a5636: # Author Link
    columnSuffix: nrtanwba
    contentColumnType: text
    fieldGroup: null
    handle: authorLink
    instructions: ''
    name: 'Author Link'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
