field: d8908cbd-ae7e-4778-b10d-2451f45de857 # Slider Matrix
fieldLayouts:
  750dc0e9-51bd-4c90-924b-7ef295656c98:
    tabs:
      -
        elements:
          -
            fieldUid: af833e7a-e9a4-4544-9622-9ae220acdc95 # Text Sub
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 4ef6bb87-f4cd-4616-9bda-46bd523e9962 # Text Heading
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: b2fc737a-5c4d-43c3-9f2a-a83984420667 # Text Background
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: d8d9f665-6ed7-4a01-8f68-5295fe71b7e0 # Slide Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 94e99070-0585-4805-86f9-3902da2745e7 # Slide Color
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  4ef6bb87-f4cd-4616-9bda-46bd523e9962: # Text Heading
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: textHeading
    instructions: ''
    name: 'Text Heading'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  94e99070-0585-4805-86f9-3902da2745e7: # Slide Color
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: slideColor
    instructions: ''
    name: 'Slide Color'
    searchable: false
    settings:
      optgroups: true
      options:
        -
          __assoc__:
            -
              - label
              - Blue
            -
              - value
              - blue
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Yellow
            -
              - value
              - yellow
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Red
            -
              - value
              - red
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - 'Dark Blue'
            -
              - value
              - darkblue
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Gray
            -
              - value
              - gray
            -
              - default
              - ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Dropdown
  af833e7a-e9a4-4544-9622-9ae220acdc95: # Text Sub
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: textSub
    instructions: ''
    name: 'Text Sub'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  b2fc737a-5c4d-43c3-9f2a-a83984420667: # Text Background
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: textBackground
    instructions: ''
    name: 'Text Background'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  d8d9f665-6ed7-4a01-8f68-5295fe71b7e0: # Slide Image
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: slideImage
    instructions: ''
    name: 'Slide Image'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
