defaultPlacement: end
enableVersioning: true
handle: authors
name: Authors
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  d7c059b5-7d24-48d7-97bf-9dfca0e647ca: # nitroblog
    enabledByDefault: true
    hasUrls: true
    template: authors/_entry
    uriFormat: 'authors/{slug}'
structure:
  maxLevels: null
  uid: 6cc139fa-a202-4172-a344-2a061968e6c9
type: structure
