defaultPlacement: end
enableVersioning: true
handle: pages
name: Pages
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  d7c059b5-7d24-48d7-97bf-9dfca0e647ca: # nitroblog
    enabledByDefault: true
    hasUrls: true
    template: null
    uriFormat: 'pages/{slug}'
structure:
  maxLevels: null
  uid: 802c6480-8153-4e86-b9dc-0c0c448cc084
type: structure
