defaultPlacement: end
enableVersioning: true
handle: speakers
name: Speakers
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  d7c059b5-7d24-48d7-97bf-9dfca0e647ca: # nitroblog
    enabledByDefault: true
    hasUrls: true
    template: null
    uriFormat: 'speakers/{slug}'
structure:
  maxLevels: null
  uid: 9019a9da-0c29-41df-9e9a-234cc7051047
type: structure
